name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies
       run: yarn install

    - name: Run tests
       run: yarn test:coverage

    - name: Build package
       run: yarn build

    # - name: Publish to npm
    #    run: npm publish
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
